"""The bronze integrity sweep.

``pytest`` tests the **code**; this tests the **data**. Neither substitutes for
the other, and both are blind to what the other sees.

Everything here is offline and deterministic. It walks ``data/bronze/``, holds
every artifact to the manifest that claims it, and holds every manifest to the
source register. Non-zero exit on any error, so it can gate a build.

⚠ **The report carries no timestamp**, deliberately. `report/qa.md` is committed,
and a generated-at line would make every run a diff — which is exactly the noise
that trains people to stop reading diffs of generated files.

⚠ **Terminal output is ASCII.** The Windows console is cp1252 by default and
raises `UnicodeEncodeError` on a tick or an em-dash. A guard that crashes on the
machine it exists to protect is worse than no guard. The markdown report is
UTF-8 and has no such restriction.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from pathlib import Path

from fpl.lib.bronze import BRONZE_ROOT, MANIFEST_NAME, ManifestEntry, read_manifest, sha256_of
from fpl.lib.sources import REGISTER_PATH, RegisterError, SourceRegister

__all__ = ["Check", "ERROR", "Report", "WARN", "main", "sweep"]

ERROR = "error"
WARN = "warn"

REPORT_PATH = Path("report/qa.md")

#: Curated CSVs are bronze, but they are hand-authored rather than fetched: no
#: manifest, no sha256, no retrieval date. Exempt from the artifact checks and
#: covered instead by the register's own validation.
MANUAL_DIR = "manual"

#: Fields a manifest entry cannot be useful without. `season` and `gameweek` are
#: absent from this list on purpose — plenty of artifacts are not gameweek-bound.
REQUIRED_FIELDS = ("source_id", "title", "url", "license", "retrieved_at", "sha256")


@dataclass(frozen=True, slots=True)
class Check:
    name: str
    passed: bool
    severity: str = ERROR
    detail: str = ""


@dataclass
class Report:
    checks: list[Check] = field(default_factory=list)

    def add(self, name: str, passed: bool, *, severity: str = ERROR, detail: str = "") -> None:
        self.checks.append(Check(name=name, passed=passed, severity=severity, detail=detail))

    @property
    def errors(self) -> list[Check]:
        return [c for c in self.checks if not c.passed and c.severity == ERROR]

    @property
    def warnings(self) -> list[Check]:
        return [c for c in self.checks if not c.passed and c.severity == WARN]

    @property
    def ok(self) -> bool:
        """⚠ Warnings do not fail the build. Only errors do."""
        return not self.errors

    def to_markdown(self) -> str:
        lines = [
            "# Bronze integrity report",
            "",
            "Generated by `fpl-qa`. Do not edit — see `report/README.md`.",
            "",
            f"**{len(self.checks)} checks · {len(self.errors)} error(s) · "
            f"{len(self.warnings)} warning(s)**",
            "",
        ]
        if not self.checks:
            lines += ["Nothing to check.", ""]
        for check in self.checks:
            mark = "PASS" if check.passed else check.severity.upper()
            lines.append(
                f"- `{mark}` {check.name}" + (f" — {check.detail}" if check.detail else "")
            )
        return "\n".join(lines) + "\n"


def sweep(root: Path = BRONZE_ROOT, register_path: Path = REGISTER_PATH) -> Report:
    """Walk bronze and hold it to its own rules."""
    report = Report()

    source_dirs = (
        sorted(p for p in root.iterdir() if p.is_dir() and p.name != MANUAL_DIR)
        if root.is_dir()
        else []
    )

    register = _check_register(report, register_path, has_artifacts=bool(source_dirs))

    for source_dir in source_dirs:
        _check_source(report, source_dir, register)

    if root.is_dir():
        strays = sorted(p for p in root.rglob("*") if p.is_file() and ".tmp" in p.name)
        report.add(
            "no interrupted writes left a temp file behind",
            not strays,
            detail=", ".join(str(p) for p in strays) if strays else "",
        )

    return report


def _check_register(
    report: Report, register_path: Path, *, has_artifacts: bool
) -> SourceRegister | None:
    try:
        register = SourceRegister.load(register_path)
    except RegisterError as exc:
        # ⚠ Severity depends on whether anything actually needs the register.
        # Before FOO-20 lands there is no register and nothing in bronze, which
        # is a legitimate state and must not be red. The moment an artifact
        # exists, an unreadable register means unprovenanced data.
        report.add(
            "the source register loads and validates",
            False,
            severity=ERROR if has_artifacts else WARN,
            detail="; ".join(exc.problems),
        )
        return None

    report.add(
        "the source register loads and validates",
        True,
        detail=f"{len(register)} source(s) registered",
    )
    return register


def _check_source(report: Report, source_dir: Path, register: SourceRegister | None) -> None:
    source_id = source_dir.name
    manifest_file = source_dir / MANIFEST_NAME

    if not manifest_file.exists():
        report.add(
            f"{source_id}: has a manifest",
            False,
            detail=(
                f"{manifest_file} is missing. Every artifact must be provenanced; "
                "an unmanifested directory is not data."
            ),
        )
        return

    try:
        entries = read_manifest(source_id, source_dir.parent)
    except Exception as exc:  # noqa: BLE001 - any parse failure is the same defect
        report.add(f"{source_id}: manifest parses", False, detail=f"{type(exc).__name__}: {exc}")
        return
    report.add(f"{source_id}: manifest parses", True, detail=f"{len(entries)} entr(ies)")

    _check_manifest_shape(report, source_id, entries, register)
    _check_files_against_manifest(report, source_dir, entries)


def _check_manifest_shape(
    report: Report, source_id: str, entries: list[ManifestEntry], register: SourceRegister | None
) -> None:
    missing = [
        f"{entry.id}.{name}"
        for entry in entries
        for name in REQUIRED_FIELDS
        if not getattr(entry, name)
    ]
    report.add(
        f"{source_id}: every entry carries source_id, title, url, licence, the day and a sha256",
        not missing,
        detail=", ".join(missing),
    )

    mismatched = [entry.id for entry in entries if entry.source_id != source_id]
    report.add(
        f"{source_id}: every entry's source_id matches its directory",
        not mismatched,
        detail=", ".join(mismatched),
    )

    ids = [entry.id for entry in entries]
    duplicates = sorted({name for name in ids if ids.count(name) > 1})
    report.add(
        f"{source_id}: manifest ids are unique",
        not duplicates,
        detail=", ".join(duplicates),
    )

    # Determinism, not correctness — hence a warning. An unsorted manifest still
    # describes the data truthfully, it just makes every rewrite a noisy diff.
    report.add(
        f"{source_id}: manifest is sorted by id",
        ids == sorted(ids),
        severity=WARN,
        detail="rewrite with write_bronze to normalise" if ids != sorted(ids) else "",
    )

    if register is not None:
        unresolved = sorted({e.source_id for e in entries if e.source_id not in register})
        report.add(
            f"{source_id}: every source_id resolves in the register",
            not unresolved,
            detail=", ".join(unresolved),
        )


def _check_files_against_manifest(
    report: Report, source_dir: Path, entries: list[ManifestEntry]
) -> None:
    source_id = source_dir.name
    on_disk = {
        path for path in source_dir.iterdir() if path.is_file() and path.name != MANIFEST_NAME
    }
    by_stem = {path.stem: path for path in on_disk}

    # ⚠ An unmanifested file is unprovenanced data, which under our own rules is
    # not data at all.
    claimed = {entry.id for entry in entries}
    orphan_files = sorted(path.name for path in on_disk if path.stem not in claimed)
    report.add(
        f"{source_id}: every file appears in the manifest",
        not orphan_files,
        detail=", ".join(orphan_files),
    )

    # ⚠ And a manifest entry with no file is a lie.
    orphan_entries = sorted(entry.id for entry in entries if entry.id not in by_stem)
    report.add(
        f"{source_id}: every manifest entry has a file",
        not orphan_entries,
        detail=", ".join(orphan_entries),
    )

    corrupt: list[str] = []
    wrong_size: list[str] = []
    for entry in entries:
        path = by_stem.get(entry.id)
        if path is None:
            continue
        data = path.read_bytes()
        if sha256_of(data) != entry.sha256:
            corrupt.append(f"{path.name} (manifest says {entry.sha256[:12]}...)")
        if entry.bytes != len(data):
            wrong_size.append(f"{path.name} (manifest says {entry.bytes}, file is {len(data)})")

    # This is the check that catches a hand-edit of bronze, which is forbidden,
    # and it is the reason data/bronze/** is marked -text in .gitattributes.
    report.add(
        f"{source_id}: every sha256 matches the bytes on disk",
        not corrupt,
        detail=", ".join(corrupt),
    )
    report.add(
        f"{source_id}: every recorded byte count matches the file",
        not wrong_size,
        detail=", ".join(wrong_size),
    )


def main(
    argv: list[str] | None = None,
    *,
    register_path: Path = REGISTER_PATH,
    report_path: Path = REPORT_PATH,
) -> int:
    """Run the sweep, write the report, return an exit code.

    ``report_path`` is a parameter rather than a module constant read directly so
    that a test can point it at a temp directory. A guard whose own test suite
    writes into the repo it guards is not a guard anyone should trust.
    """
    argv = sys.argv[1:] if argv is None else argv
    root = Path(argv[0]) if argv else BRONZE_ROOT

    report = sweep(root, register_path)

    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(report.to_markdown(), encoding="utf-8")

    # ASCII only: see the module docstring.
    print(
        f"qa: {len(report.checks)} checks, "
        f"{len(report.errors)} error(s), {len(report.warnings)} warning(s) "
        f"-> {report_path}"
    )
    for check in report.errors:
        print(f"  ERROR {check.name}" + (f" -- {check.detail}" if check.detail else ""))
    for check in report.warnings:
        print(f"  WARN  {check.name}" + (f" -- {check.detail}" if check.detail else ""))

    return 0 if report.ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
